// Dummy data for local development. Replace with real API data once your
// backend/API route for businesses is ready.

export const allBusinesses = [
  // ── Handicrafts ──────────────────────────────────────────────
  {
    slug: "earthy-hands-pottery",
    name: "Earthy Hands Pottery",
    listingType: "Products",
    category: "Handicrafts",
    type: "Retail Shop",
    rating: 4.8,
    reviews: 120,
    distance: "1.2 km",
    address: "Ballygunge, Kolkata",
    img: "https://picsum.photos/seed/earthy-hands-pottery/400/300",
    lat: 22.5245,
    lng: 88.3644,
  },
  {
    slug: "weave-magic",
    name: "Weave Magic",
    listingType: "Products",
    category: "Handicrafts",
    type: "Home-based",
    rating: 4.7,
    reviews: 98,
    distance: "2.3 km",
    address: "Shyambazar, Kolkata",
    img: "https://picsum.photos/seed/weave-magic/400/300",
    lat: 22.6014,
    lng: 88.3733,
  },
  {
    slug: "crafts-of-odisha",
    name: "Crafts of Odisha",
    listingType: "Products",
    category: "Handicrafts",
    type: "Retail Shop",
    rating: 4.6,
    reviews: 48,
    distance: "1.4 km",
    address: "Gariahat, Kolkata",
    img: "https://picsum.photos/seed/crafts-of-odisha/400/300",
    lat: 22.5186,
    lng: 88.3654,
  },

  // ── Local Food ───────────────────────────────────────────────
  {
    slug: "pure-and-natural",
    name: "Pure & Natural",
    listingType: "Products",
    category: "Local Food",
    type: "Retail Shop",
    rating: 4.9,
    reviews: 76,
    distance: "1.5 km",
    address: "Salt Lake, Kolkata",
    img: "https://picsum.photos/seed/pure-and-natural/400/300",
    lat: 22.5806,
    lng: 88.4166,
  },
  {
    slug: "mishti-corner",
    name: "Mishti Corner",
    listingType: "Products",
    category: "Local Food",
    type: "Retail Shop",
    rating: 4.5,
    reviews: 54,
    distance: "1.3 km",
    address: "College Street, Kolkata",
    img: "https://picsum.photos/seed/mishti-corner/400/300",
    lat: 22.5745,
    lng: 88.3628,
  },
  {
    slug: "green-valley-farms",
    name: "Green Valley Farms",
    listingType: "Products",
    category: "Local Food",
    type: "Farm / Producer",
    rating: 4.6,
    reviews: 88,
    distance: "2.0 km",
    address: "Behala, Kolkata",
    img: "https://picsum.photos/seed/green-valley-farms/400/300",
    lat: 22.4989,
    lng: 88.3145,
  },

  // ── Organic ──────────────────────────────────────────────────
  {
    slug: "dinesh-organics",
    name: "Dinesh Organics",
    listingType: "Products",
    category: "Organic",
    type: "Farm / Producer",
    rating: 4.4,
    reviews: 61,
    distance: "3.1 km",
    address: "Tollygunge, Kolkata",
    img: "https://picsum.photos/seed/dinesh-organics/400/300",
    lat: 22.4989,
    lng: 88.3467,
  },
  {
    slug: "farm-fresh-basket",
    name: "Farm Fresh Basket",
    listingType: "Products",
    category: "Organic",
    type: "Online Only",
    rating: 4.3,
    reviews: 39,
    distance: "4.2 km",
    address: "New Town, Kolkata",
    img: "https://picsum.photos/seed/farm-fresh-basket/400/300",
    lat: 22.5867,
    lng: 88.4614,
  },

  // ── Clothing ─────────────────────────────────────────────────
  {
    slug: "bengal-weaves",
    name: "Bengal Weaves",
    listingType: "Products",
    category: "Clothing",
    type: "Retail Shop",
    rating: 4.5,
    reviews: 72,
    distance: "1.8 km",
    address: "Hatibagan, Kolkata",
    img: "https://picsum.photos/seed/bengal-weaves/400/300",
    lat: 22.6013,
    lng: 88.3733,
  },
  {
    slug: "crafts-of-bengal",
    name: "Crafts of Bengal",
    listingType: "Products",
    category: "Clothing",
    type: "Retail Shop",
    rating: 4.7,
    reviews: 98,
    distance: "0.8 km",
    address: "Park Street, Kolkata",
    img: "https://picsum.photos/seed/crafts-of-bengal/400/300",
    lat: 22.5527,
    lng: 88.3529,
  },

  // ── Home Decor ───────────────────────────────────────────────
  {
    slug: "home-decor-kolkata",
    name: "Home Decor Kolkata",
    listingType: "Products",
    category: "Home Decor",
    type: "Retail Shop",
    rating: 4.4,
    reviews: 75,
    distance: "2.1 km",
    address: "Lake Town, Kolkata",
    img: "https://picsum.photos/seed/home-decor-kolkata/400/300",
    lat: 22.6067,
    lng: 88.4048,
  },
  {
    slug: "clay-and-co",
    name: "Clay & Co.",
    listingType: "Products",
    category: "Home Decor",
    type: "Home-based",
    rating: 4.6,
    reviews: 41,
    distance: "1.9 km",
    address: "Howrah, Kolkata",
    img: "https://picsum.photos/seed/clay-and-co/400/300",
    lat: 22.5958,
    lng: 88.2636,
  },

  // ── Services: Maid ───────────────────────────────────────────
  {
    slug: "priya-home-help",
    name: "Priya's Home Help",
    listingType: "Services",
    category: "Maid",
    type: "Service Provider",
    rating: 4.7,
    reviews: 34,
    distance: "1.1 km",
    address: "Jadavpur, Kolkata",
    img: "https://picsum.photos/seed/priya-home-help/400/300",
    lat: 22.4997,
    lng: 88.3714,
  },
  {
    slug: "sparkle-clean-services",
    name: "Sparkle Clean Services",
    listingType: "Services",
    category: "Maid",
    type: "Service Provider",
    rating: 4.3,
    reviews: 27,
    distance: "2.6 km",
    address: "Dum Dum, Kolkata",
    img: "https://picsum.photos/seed/sparkle-clean/400/300",
    lat: 22.6420,
    lng: 88.4210,
  },

  // ── Services: Teacher ────────────────────────────────────────
  {
    slug: "bright-minds-tuition",
    name: "Bright Minds Tuition",
    listingType: "Services",
    category: "Teacher",
    type: "Service Provider",
    rating: 4.9,
    reviews: 52,
    distance: "1.7 km",
    address: "South City, Kolkata",
    img: "https://picsum.photos/seed/bright-minds-tuition/400/300",
    lat: 22.4991,
    lng: 88.3936,
  },
  {
    slug: "mrs-sen-piano-tutor",
    name: "Mrs. Sen — Piano Tutor",
    listingType: "Services",
    category: "Teacher",
    type: "Home-based",
    rating: 4.8,
    reviews: 19,
    distance: "3.4 km",
    address: "Alipore, Kolkata",
    img: "https://picsum.photos/seed/piano-tutor/400/300",
    lat: 22.5327,
    lng: 88.3325,
  },

  // ── Services: Plumber ────────────────────────────────────────
  {
    slug: "rapid-fix-plumbing",
    name: "Rapid Fix Plumbing",
    listingType: "Services",
    category: "Plumber",
    type: "Service Provider",
    rating: 4.5,
    reviews: 63,
    distance: "1.0 km",
    address: "Kasba, Kolkata",
    img: "https://picsum.photos/seed/rapid-fix-plumbing/400/300",
    lat: 22.5142,
    lng: 88.3892,
  },
  {
    slug: "kolkata-pipe-doctors",
    name: "Kolkata Pipe Doctors",
    listingType: "Services",
    category: "Plumber",
    type: "Service Provider",
    rating: 4.2,
    reviews: 45,
    distance: "2.9 km",
    address: "Barrackpore, Kolkata",
    img: "https://picsum.photos/seed/pipe-doctors/400/300",
    lat: 22.7663,
    lng: 88.3703,
  },
  {
    slug: "clay-and-co",
    name: "Clay & Co.",
    listingType: "Products",
    category: "Home Decor",
    type: "Handicrafts",
    rating: 4.6,
    reviews: 41,
    distance: "1.9 km",
    address: "Howrah, Kolkata",
    lat: 22.4870,
    lng: 88.3810,
    img: "https://images.unsplash.com/photo-1605000797499-95a51c5269ae?w=400&q=80",
    verified: true,
    phone: "+91 98765 11111",
    hours: "Mon - Sat: 10:00 AM - 7:00 PM",
    description: "Handcrafted terracotta home decor pieces made by local artisans in Howrah.",
  },
  {
    slug: "baghajatin-honey-house",
    name: "Baghajatin Honey House",
    listingType: "Products",
    category: "Local Food",
    type: "Food & Beverages",
    rating: 4.7,
    reviews: 58,
    distance: "0.8 km",
    address: "Baghajatin, Kolkata",
    lat: 22.4830,
    lng: 88.3745,
    img: "https://www.dineshflourmills.com/cdn/shop/files/OrganicHoney_1.jpg?v=1770623215",
    verified: true,
    phone: "+91 98765 22222",
    hours: "Mon - Sun: 9:00 AM - 8:00 PM",
    description: "Locally sourced raw honey, sold fresh from the family apiary.",
  },
  {
    slug: "subodh-street-weavers",
    name: "Subodh Street Weavers",
    listingType: "Products",
    category: "Handicrafts",
    type: "Handicrafts",
    rating: 4.5,
    reviews: 33,
    distance: "1.3 km",
    address: "Raja Subodh Chandra Mallick Rd, Kolkata",
    lat: 22.4780,
    lng: 88.3700,
    img: "https://images.unsplash.com/photo-1590874103328-eac38a683ce7?w=400&q=80",
    verified: false,
    phone: "+91 98765 33333",
    hours: "Mon - Sat: 10:30 AM - 6:30 PM",
    description: "Handwoven bags and textiles from a small weaving cooperative.",
  },
  {
    slug: "jatin-nagar-tea-stall",
    name: "Jatin Nagar Tea Stall",
    listingType: "Products",
    category: "Local Food",
    type: "Food & Beverages",
    rating: 4.4,
    reviews: 27,
    distance: "2.6 km",
    address: "Baghajatin Colony, Kolkata",
    lat: 22.4950,
    lng: 88.3900,
    img: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&q=80",
    verified: false,
    phone: "+91 98765 44444",
    hours: "Mon - Sun: 6:00 AM - 9:00 PM",
    description: "A neighborhood favorite for chai and traditional Bengali snacks.",
  },
  {
    slug: "kasba-woodcraft",
    name: "Kasba Woodcraft",
    listingType: "Products",
    category: "Home Decor",
    type: "Handicrafts",
    rating: 4.3,
    reviews: 19,
    distance: "4.2 km",
    address: "Kasba, Kolkata",
    lat: 22.5142,
    lng: 88.3892,
    img: "https://images.unsplash.com/photo-1579762715118-a6f1d4b934f1?w=400&q=80",
    verified: true,
    phone: "+91 98765 55555",
    hours: "Mon - Sat: 11:00 AM - 7:00 PM",
    description: "Custom wooden furniture and decor pieces, made to order.",
  },
];
export const getBusinessBySlug = (slug) => allBusinesses.find((b) => b.slug === slug);

export const getRelatedBusinesses = (currentSlug, limit = 3) =>
  allBusinesses.filter((b) => b.slug !== currentSlug).slice(0, limit);