// src/lib/products.js
export const allProducts = [
  {
    slug: "hand-painted-terracotta-pot",
    name: "Hand Painted Terracotta Pot",
    seller: "Earthy Hands Pottery",
    sellerRating: 4.8,
    sellerReviews: 230,
    sellerProducts: 120,
    sellerLocation: "Kolkata, India",
    verified: true,
    price: 130850,
    rating: 3,
    reviews: 120,
    inStock: true,
    stockCount: 20,
    badge: "Bestseller",
    category: "Handicrafts",
    breadcrumbCategory: "Handicrafts",
    images: [
      "https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=600&q=80",
      "https://images.unsplash.com/photo-1605000797499-95a51c5269ae?w=600&q=80",
    ],
    description:
      "Beautiful hand-painted terracotta pot crafted by local artisans using traditional techniques. Ideal for cooking, serving, and home decoration.",
    features: ["100% Handmade", "Natural & Safe", "Traditional Craft", "Sustainable Product"],
    specs: {
      Material: "Natural Clay",
      Color: "Brown",
      Origin: "Kolkata",
      Category: "Handicrafts",
    },
    customerReviews: [
      { name: "Rahul Verma", avatar: "https://randomuser.me/api/portraits/men/32.jpg", verified: true, rating: 3.5, timeAgo: "5 days ago", text: "Good quality, but the color was slightly different than shown online." },
    ],
  },
  {
    slug: "organic-wild-honey",
    name: "Organic Wild Honey",
    seller: "Pure & Natural",
    sellerRating: 4.9,
    sellerReviews: 76,
    sellerProducts: 30,
    sellerLocation: "Kolkata, India",
    verified: true,
    price: 650,
    rating: 4,
    reviews: 96,
    inStock: true,
    stockCount: 40,
    badge: "New",
    category: "Local Food",
    breadcrumbCategory: "Local Food",
    images: ["https://www.dineshflourmills.com/cdn/shop/files/OrganicHoney_1.jpg?v=1770623215"],
    description: "Pure, unprocessed wild honey sourced directly from local forests.",
    features: ["100% Pure", "No Additives", "Cold Extracted"],
    specs: { Volume: "500 ml", Origin: "Kolkata", Category: "Local Food" },
    customerReviews: [],
  },
  {
    slug: "handwoven-tribal-bag",
    name: "Handwoven Tribal Bag",
    seller: "Weave Magic",
    sellerRating: 4.6,
    sellerReviews: 85,
    sellerProducts: 60,
    sellerLocation: "Kolkata, India",
    verified: true,
    price: 1250,
    rating: 4,
    reviews: 80,
    inStock: true,
    stockCount: 15,
    badge: "Bestseller",
    category: "Handicrafts",
    breadcrumbCategory: "Handicrafts",
    images: ["https://images.unsplash.com/photo-1590874103328-eac38a683ce7?w=600&q=80"],
    description: "Handwoven tribal bag crafted by skilled artisans using traditional weaving techniques.",
    features: ["Handwoven", "Durable Fabric", "Traditional Design"],
    specs: { Material: "Cotton Blend", Color: "Multicolor", Origin: "Kolkata", Category: "Handicrafts" },
    customerReviews: [],
  },
  {
    slug: "masala-spice-mix",
    name: "Masala Spice Mix",
    seller: "Spice Story",
    sellerRating: 4.5,
    sellerReviews: 110,
    sellerProducts: 25,
    sellerLocation: "Kolkata, India",
    verified: false,
    price: 350,
    rating: 4,
    reviews: 110,
    inStock: true,
    stockCount: 50,
    badge: null,
    category: "Local Food",
    breadcrumbCategory: "Local Food",
    images: ["https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&q=80"],
    description: "A fragrant blend of hand-picked spices for authentic home cooking.",
    features: ["Hand Blended", "Natural Spices"],
    specs: { Weight: "250 g", Origin: "Kolkata", Category: "Local Food" },
    customerReviews: [],
  },
  {
    slug: "macrame-wall-hanging",
    name: "Macrame Wall Hanging",
    seller: "Home Decor Kolkata",
    sellerRating: 4.2,
    sellerReviews: 75,
    sellerProducts: 40,
    sellerLocation: "Kolkata, India",
    verified: false,
    price: 950,
    rating: 2,
    reviews: 75,
    inStock: true,
    stockCount: 10,
    badge: null,
    category: "Home Decor",
    breadcrumbCategory: "Home Decor",
    images: ["https://images.unsplash.com/photo-1610701596007-11502861dcfa?w=600&q=80"],
    description: "Intricately handwoven macrame wall hanging that adds a rustic, artisanal touch to any room.",
    features: ["Handwoven", "Natural Fibers"],
    specs: { Material: "Macrame Cotton", Origin: "Kolkata", Category: "Home Decor" },
    customerReviews: [],
  },
  {
    slug: "handmade-herbal-soap",
    name: "Handmade Herbal Soap",
    seller: "Nature Touch",
    sellerRating: 4.7,
    sellerReviews: 60,
    sellerProducts: 35,
    sellerLocation: "Kolkata, India",
    verified: true,
    price: 299,
    rating: 4,
    reviews: 60,
    inStock: true,
    stockCount: 60,
    badge: "New",
    category: "Organic",
    breadcrumbCategory: "Organic",
    images: ["https://lovelygreens.com/wp-content/uploads/herbal-soap-calendula.jpg"],
    description: "Natural handmade soap crafted with herbal ingredients, free from harsh chemicals.",
    features: ["100% Natural", "Herbal Ingredients", "Handmade"],
    specs: { Weight: "100 g", Origin: "Kolkata", Category: "Organic" },
    customerReviews: [],
  },
  {
    slug: "cold-pressed-mustard-oil",
    name: "Cold Pressed Mustard Oil",
    seller: "Green Valley Farms",
    sellerRating: 4.6,
    sellerReviews: 88,
    sellerProducts: 20,
    sellerLocation: "Kolkata, India",
    verified: true,
    price: 320,
    rating: 2,
    reviews: 88,
    inStock: true,
    stockCount: 45,
    badge: null,
    category: "Organic",
    breadcrumbCategory: "Organic",
    images: ["https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80"],
    description: "Traditionally cold-pressed mustard oil, retaining natural nutrients and flavor.",
    features: ["Cold Pressed", "No Additives", "Traditional Method"],
    specs: { Volume: "1 L", Origin: "Kolkata", Category: "Organic" },
    customerReviews: [],
  },
  {
    slug: "handwoven-cotton-stole",
    name: "Handwoven Cotton Stole",
    seller: "Weave Magic",
    sellerRating: 4.6,
    sellerReviews: 64,
    sellerProducts: 60,
    sellerLocation: "Kolkata, India",
    verified: true,
    price: 780,
    rating: 1,
    reviews: 64,
    inStock: true,
    stockCount: 12,
    badge: "Bestseller",
    category: "Clothing",
    breadcrumbCategory: "Clothing",
    images: ["https://aankona.com/cdn/shop/files/IMG_20240201_120548.jpg?v=1718688470&width=1080"],
    description: "Lightweight handwoven cotton stole, perfect for everyday wear.",
    features: ["Handwoven", "Breathable Fabric"],
    specs: { Material: "Cotton", Origin: "Kolkata", Category: "Clothing" },
    customerReviews: [
      { name: "Anita Das", avatar: "https://randomuser.me/api/portraits/women/68.jpg", verified: false, rating: 1, timeAgo: "2 weeks ago", text: "Fabric felt thinner than expected and started fraying after one wash." },
    ],
  },
  {
    slug: "muri-mixture",
    name: "Muri Mixture",
    seller: "Bengal Traditions",
    sellerRating: 4.8,
    sellerReviews: 42,
    sellerProducts: 18,
    sellerLocation: "Kolkata, India",
    verified: false,
    price: 120,
    rating: 5,
    reviews: 42,
    inStock: true,
    stockCount: 80,
    badge: null,
    category: "Local Food",
    breadcrumbCategory: "Local Food",
    images: ["https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=600&q=80"],
    description: "Classic Bengali puffed rice snack mix, crunchy and flavorful.",
    features: ["Freshly Made", "No Preservatives"],
    specs: { Weight: "200 g", Origin: "Kolkata", Category: "Local Food" },
    customerReviews: [],
  },
  {
    slug: "homemade-mixed-fruit-jam",
    name: "Homemade Mixed Fruit Jam",
    seller: "Pure & Natural",
    sellerRating: 4.5,
    sellerReviews: 55,
    sellerProducts: 30,
    sellerLocation: "Kolkata, India",
    verified: true,
    price: 280,
    rating: 2,
    reviews: 55,
    inStock: true,
    stockCount: 30,
    badge: null,
    category: "Local Food",
    breadcrumbCategory: "Local Food",
    images: [
      "https://images.squarespace-cdn.com/content/v1/53fc8c7ce4b0af221e1c4c06/1606152556979-GIY61SNGPCPHFST6JMEL/82B7E991-EF2F-4EBE-B6C5-373D9207C1A8_1_201_a.jpeg",
    ],
    description: "Homemade mixed fruit jam made with seasonal fruits and minimal sugar.",
    features: ["Homemade", "Seasonal Fruits", "Low Sugar"],
    specs: { Weight: "350 g", Origin: "Kolkata", Category: "Local Food" },
    customerReviews: [],
  },
  {
    slug: "wooden-coaster-set",
    name: "Wooden Coaster Set",
    seller: "Artisan Woodcraft",
    sellerRating: 4.4,
    sellerReviews: 38,
    sellerProducts: 22,
    sellerLocation: "Kolkata, India",
    verified: false,
    price: 450,
    rating: 4,
    reviews: 38,
    inStock: true,
    stockCount: 25,
    badge: null,
    category: "Handicrafts",
    breadcrumbCategory: "Handicrafts",
    images: ["https://images.unsplash.com/photo-1579762715118-a6f1d4b934f1?w=600&q=80"],
    description: "Set of hand-carved wooden coasters, a functional and elegant table accessory.",
    features: ["Hand-Carved", "Solid Wood", "Set of 6"],
    specs: { Material: "Sheesham Wood", Origin: "Kolkata", Category: "Handicrafts" },
    customerReviews: [],
  },
  {
    slug: "darjeeling-green-tea",
    name: "Darjeeling Green Tea",
    seller: "Hills & Herbs",
    sellerRating: 4.7,
    sellerReviews: 92,
    sellerProducts: 15,
    sellerLocation: "Kolkata, India",
    verified: true,
    price: 550,
    rating: 3,
    reviews: 92,
    inStock: true,
    stockCount: 35,
    badge: null,
    category: "Local Food",
    breadcrumbCategory: "Local Food",
    images: ["https://images.unsplash.com/photo-1500651230702-0e2d8a49d4ad?w=600&q=80"],
    description: "Premium Darjeeling green tea leaves, sourced from high-altitude gardens.",
    features: ["High Altitude", "Single Origin", "Antioxidant Rich"],
    specs: { Weight: "100 g", Origin: "Darjeeling", Category: "Local Food" },
    customerReviews: [],
  },
  {
    slug: "bamboo-craft-set",
    name: "Bamboo Craft Set",
    seller: "Bamboo Works",
    sellerRating: 4.7,
    sellerReviews: 64,
    sellerProducts: 20,
    sellerLocation: "Kolkata, India",
    verified: false,
    price: 1100,
    rating: 4,
    reviews: 64,
    inStock: true,
    stockCount: 18,
    badge: "New",
    category: "Handicrafts",
    breadcrumbCategory: "Handicrafts",
    images: ["https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=600&q=80"],
    description: "A handcrafted bamboo set made using traditional weaving techniques by local artisans.",
    features: ["Handwoven Bamboo", "Eco-Friendly", "Durable Finish"],
    specs: { Material: "Bamboo", Origin: "Kolkata", Category: "Handicrafts" },
    customerReviews: [],
  },
  {
    slug: "handmade-soap-bar",
    name: "Handmade Soap Bar",
    seller: "Nature Bliss",
    sellerRating: 4.9,
    sellerReviews: 200,
    sellerProducts: 35,
    sellerLocation: "Kolkata, India",
    verified: true,
    price: 199,
    rating: 3,
    reviews: 200,
    inStock: true,
    stockCount: 60,
    badge: null,
    category: "Organic",
    breadcrumbCategory: "Organic",
    images: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQd2CEY4ulGSvsjqboReoXOgus0mbMEvap_34tL0z9TXpuNTK0Jc1UDHJ1G&s=10",
    ],
    description: "Natural handmade soap bar crafted with herbal ingredients, free from harsh chemicals.",
    features: ["100% Natural", "Herbal Ingredients", "Handmade", "Chemical Free"],
    specs: { Weight: "100 g", Origin: "Kolkata", Category: "Organic" },
    customerReviews: [],
  },
  {
    slug: "wooden-jewellery-box",
    name: "Wooden Jewellery Box",
    seller: "Craft Kart",
    sellerRating: 4.5,
    sellerReviews: 55,
    sellerProducts: 28,
    sellerLocation: "Kolkata, India",
    verified: false,
    price: 780,
    rating: 4,
    reviews: 55,
    inStock: true,
    stockCount: 12,
    badge: "Bestseller",
    category: "Handicrafts",
    breadcrumbCategory: "Handicrafts",
    images: [
      "https://5.imimg.com/data5/SELLER/Default/2023/1/HS/ZH/CN/182213604/engraved-wooden-jewellery-box-with-mirror-10in-x-6in-x-4in-.jpg",
    ],
    description: "Elegant hand-carved wooden jewellery box made by skilled local craftsmen.",
    features: ["Hand-Carved", "Solid Wood", "Traditional Craft"],
    specs: { Material: "Sheesham Wood", Origin: "Kolkata", Category: "Handicrafts" },
    customerReviews: [],
  },
  {
    slug: "tribal-beaded-necklace",
    name: "Tribal Beaded Necklace",
    seller: "Crafts of Odisha",
    sellerRating: 4.6,
    sellerReviews: 48,
    sellerProducts: 40,
    sellerLocation: "Kolkata, India",
    verified: true,
    price: 420,
    rating: 4,
    reviews: 48,
    inStock: true,
    stockCount: 22,
    badge: null,
    category: "Clothing",
    breadcrumbCategory: "Clothing",
    images: ["https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=600&q=80"],
    description: "Handcrafted tribal beaded necklace, made using traditional bead-working techniques.",
    features: ["Handcrafted", "Traditional Design"],
    specs: { Material: "Wooden Beads", Origin: "Odisha", Category: "Clothing" },
    customerReviews: [],
  },
  {
    slug: "clay-diya-set",
    name: "Clay Diya Set",
    seller: "Earthy Hands Pottery",
    sellerRating: 4.8,
    sellerReviews: 70,
    sellerProducts: 120,
    sellerLocation: "Kolkata, India",
    verified: true,
    price: 220,
    rating: 4,
    reviews: 70,
    inStock: true,
    stockCount: 100,
    badge: "New",
    category: "Handicrafts",
    breadcrumbCategory: "Handicrafts",
    images: ["https://images.unsplash.com/photo-1605000797499-95a51c5269ae?w=600&q=80"],
    description: "Traditional clay diya set, hand-molded and perfect for festive lighting.",
    features: ["Hand-Molded", "Natural Clay", "Set of 12"],
    specs: { Material: "Natural Clay", Origin: "Kolkata", Category: "Handicrafts" },
    customerReviews: [],
  },
  {
    slug: "mustard-pickle-jar",
    name: "Mustard Pickle Jar",
    seller: "Green Valley Farms",
    sellerRating: 4.6,
    sellerReviews: 33,
    sellerProducts: 20,
    sellerLocation: "Kolkata, India",
    verified: true,
    price: 180,
    rating: 4,
    reviews: 33,
    inStock: true,
    stockCount: 40,
    badge: null,
    category: "Organic",
    breadcrumbCategory: "Organic",
    images: ["https://images.unsplash.com/photo-1601493700631-2b16ec4b4716?w=600&q=80"],
    description: "Tangy homemade mustard pickle, made with locally sourced ingredients.",
    features: ["Homemade", "No Preservatives"],
    specs: { Weight: "300 g", Origin: "Kolkata", Category: "Organic" },
    customerReviews: [],
  },
];

export const getProductBySlug = (slug) => allProducts.find((p) => p.slug === slug);

export const getRelatedProducts = (currentSlug, limit = 4) =>
  allProducts.filter((p) => p.slug !== currentSlug).slice(0, limit);